"""STL format export for CAD solids using real tessellation.

STL (STereoLithography) is a triangulated mesh format widely used for 3D printing.
This implementation uses Open CASCADE's tessellation engine to generate real geometry.
"""
import struct
from pathlib import Path
from typing import List, Any, Dict

from OCC.Core.TopoDS import TopoDS_Shape

# Import tessellation utilities from cad_kernel
import sys
from pathlib import Path as PathLib
sys.path.insert(0, str(PathLib(__file__).parent.parent))
from cad_kernel.tessellation import MeshGenerator, TessellationConfig, Triangle


def export_stl(
    shapes: List[TopoDS_Shape],
    file_path: str,
    tessellation_quality: str = "standard",
    ascii_format: bool = False
) -> Dict[str, Any]:
    """Export solids to STL format with real tessellation.

    Args:
        shapes: List of TopoDS_Shape objects to export
        file_path: Output file path (.stl)
        tessellation_quality: Quality preset (preview, standard, high_quality)
        ascii_format: If True, write ASCII STL; otherwise binary

    Returns:
        Export report with statistics

    Raises:
        ValueError: If invalid quality preset
        RuntimeError: If tessellation or file write fails
    """
    output_path = Path(file_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Ensure .stl extension
    if output_path.suffix.lower() != '.stl':
        output_path = output_path.with_suffix('.stl')

    # Get tessellation config
    try:
        config = TessellationConfig.from_name(tessellation_quality)
    except ValueError as e:
        raise ValueError(f"Invalid tessellation quality: {e}")

    # Tessellate all shapes and collect triangles
    all_triangles: List[Triangle] = []

    for shape in shapes:
        triangles = MeshGenerator.tessellate_shape(shape, config)
        all_triangles.extend(triangles)

    if not all_triangles:
        raise RuntimeError("Tessellation produced no triangles - shapes may be invalid")

    # Write STL file
    if ascii_format:
        _write_ascii_stl(output_path, all_triangles)
    else:
        _write_binary_stl(output_path, all_triangles)

    file_size = output_path.stat().st_size

    return {
        "file_path": str(output_path.absolute()),
        "format": "stl",
        "entity_count": len(shapes),
        "triangle_count": len(all_triangles),
        "file_size": file_size,
        "tessellation_config": {
            "linear_deflection": config.linear_deflection,
            "angular_deflection": config.angular_deflection,
            "quality": config.name
        },
        "data_loss": True,  # STL loses exact geometry (only mesh)
        "notes": [
            "STL format is triangulated mesh - exact geometry information is lost",
            "Suitable for 3D printing and visualization",
            "For CAD-to-CAD exchange, use STEP format instead"
        ]
    }


def _write_ascii_stl(file_path: Path, triangles: List[Triangle]) -> None:
    """Write ASCII STL file.

    Args:
        file_path: Output file path
        triangles: List of Triangle objects
    """
    with open(file_path, 'w') as f:
        f.write("solid exported\n")

        for tri in triangles:
            normal = tri.normal
            vertices = tri.vertices

            f.write(f"  facet normal {normal[0]:.6e} {normal[1]:.6e} {normal[2]:.6e}\n")
            f.write("    outer loop\n")
            for vertex in vertices:
                f.write(f"      vertex {vertex[0]:.6e} {vertex[1]:.6e} {vertex[2]:.6e}\n")
            f.write("    endloop\n")
            f.write("  endfacet\n")

        f.write("endsolid exported\n")


def _write_binary_stl(file_path: Path, triangles: List[Triangle]) -> None:
    """Write binary STL file.

    Binary STL format (little-endian):
    - Header: 80 bytes (arbitrary text)
    - Triangle count: 4 bytes (uint32)
    - For each triangle (50 bytes):
      - Normal: 12 bytes (3 x float32)
      - Vertex 1: 12 bytes (3 x float32)
      - Vertex 2: 12 bytes (3 x float32)
      - Vertex 3: 12 bytes (3 x float32)
      - Attribute: 2 bytes (uint16, usually 0)

    Args:
        file_path: Output file path
        triangles: List of Triangle objects
    """
    with open(file_path, 'wb') as f:
        # Header (80 bytes) - include generator info
        header_text = "Binary STL - Generated by CAD System with Open CASCADE"
        header = header_text.encode('ascii')[:80].ljust(80, b' ')
        f.write(header)

        # Triangle count (4 bytes, unsigned int, little-endian)
        f.write(struct.pack('<I', len(triangles)))

        # Write each triangle (50 bytes each)
        for tri in triangles:
            # Normal vector (3 floats, 12 bytes)
            f.write(struct.pack('<fff', *tri.normal))

            # Three vertices (9 floats, 36 bytes total)
            for vertex in tri.vertices:
                f.write(struct.pack('<fff', *vertex))

            # Attribute byte count (2 bytes, usually 0)
            f.write(struct.pack('<H', 0))
